In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [60]:
data1 = pd.read_csv("image_code_output.csv")
data1.head()

          code                                         image_path
0  271002935.0  unzipped_data/1/WhatsApp Image 2026-04-29 at 1...
1   10028269.0  unzipped_data/1/WhatsApp Image 2026-04-29 at 1...
2   10028268.0  unzipped_data/1/WhatsApp Image 2026-04-29 at 1...
3   10025542.0  unzipped_data/1/WhatsApp Image 2026-04-29 at 1...
4   10027276.0  unzipped_data/1/WhatsApp Image 2026-04-29 at 1...

In [61]:
data2 = pd.read_csv("AI ML Task Sheet.csv")
data2 = data2.loc[:, ~data2.columns.str.startswith('Unnamed')]
data2

                    date        code   qty    rate
0    2026-04-22 14:50:52    500001.0  16.0  1296.0
1    2026-04-22 14:50:52    500001.0   4.0  1295.0
2    2026-04-22 14:50:52    500001.0  16.0  1295.0
3    2026-04-22 14:50:52    500001.0   4.0  1295.0
4    2026-04-22 14:50:52  10029028.0   4.0  1250.0
..                   ...         ...   ...     ...
994                  NaN         NaN   NaN     NaN
995                  NaN         NaN   NaN     NaN
996                  NaN         NaN   NaN     NaN
997                  NaN         NaN   NaN     NaN
998                  NaN         NaN   NaN     NaN

[999 rows x 4 columns]

In [62]:
merged_data = pd.merge(data1, data2, on='code', how='inner')
merged_data_cleaned = merged_data.dropna()

In [63]:
merged_data_cleaned['code'] = merged_data_cleaned['code'].astype('Int64')
merged_data_cleaned['qty'] = merged_data_cleaned['qty'].astype('Int64')

In [64]:
df = merged_data_cleaned.copy()
df = df.groupby('code').agg({
    'image_path': 'first',
    'qty': 'sum',
    'rate': 'first',
    'date': 'first'
}).reset_index()

In [65]:
df

,code,image_path,qty,rate,date
0,500001,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,1032,1296.0,2026-04-22 14:50:52
1,10016728,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,24,875.0,2025-10-13 21:10:10
2,10019275,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,56,1650.0,2025-11-01 17:51:45
3,10021130,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,32,875.0,2025-11-27 13:19:14
4,10021131,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,28,875.0,2025-11-27 13:19:14
...,...,...,...,...,...
121,10029443,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,15,995.0,2026-04-27 19:03:28
122,10029444,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,15,995.0,2026-04-28 11:32:30
123,10029447,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,850.0,2026-04-28 19:13:19
124,10029448,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,850.0,2026-04-28 19:13:19
125,10029463,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,695.0,2026-04-28 11:10:59

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   code        126 non-null    Int64
 1   image_path  126 non-null    str
 2   qty         126 non-null    Int64
 3   rate        126 non-null    float64
 4   date        126 non-null    str
dtypes: Int64(2), float64(1), str(2)
memory usage: 15.2 KB

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [69]:
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df

,code,image_path,qty,rate,date,month,year
0,500001,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,1032,1296.0,2026-04-22 14:50:52,4,2026
1,10016728,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,24,875.0,2025-10-13 21:10:10,10,2025
2,10019275,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,56,1650.0,2025-11-01 17:51:45,11,2025
3,10021130,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,32,875.0,2025-11-27 13:19:14,11,2025
4,10021131,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,28,875.0,2025-11-27 13:19:14,11,2025
...,...,...,...,...,...,...,...
121,10029443,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,15,995.0,2026-04-27 19:03:28,4,2026
122,10029444,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,15,995.0,2026-04-28 11:32:30,4,2026
123,10029447,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,850.0,2026-04-28 19:13:19,4,2026
124,10029448,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,850.0,2026-04-28 19:13:19,4,2026
125,10029463,unzipped_data/1/WhatsApp Image 2026-04-29 at 1...,4,695.0,2026-04-28 11:10:59,4,2026

In [ ]:
import calendar
top3 = (
    df.groupby(['year', 'month', 'code'])['qty']
    .sum()
    .reset_index()
    .sort_values(['year', 'month', 'qty'], ascending=[True, True, False])
    .groupby(['year', 'month'])
    .head(3)
    .reset_index(drop=True)  
)

top3['month_name'] = top3['month'].apply(lambda x: calendar.month_abbr[x])
top3['period']     = top3['month_name'] + ' ' + top3['year'].astype(str)

top3[['period', 'code', 'qty']]

      period      code   qty
0   Oct 2025  10016728    24
1   Nov 2025  10019275    56
2   Nov 2025  10021130    32
3   Nov 2025  10021131    28
4   Jan 2026  10022091    84
5   Feb 2026  10022578    60
6   Feb 2026  10025105    47
7   Mar 2026  10025542    71
8   Mar 2026  10025820    28
9   Apr 2026    500001  1032
10  Apr 2026  10028268   110
11  Apr 2026  10028269    72

In [82]:
most_sold = (
    df.groupby(['year', 'month', 'code'])['qty']
    .sum()
    .reset_index()
    .sort_values(['year', 'month', 'qty'], ascending=[True, True, False])
    .groupby(['year', 'month'])
    .first()
    .reset_index()
)

most_sold['month_name'] = most_sold['month'].apply(lambda x: calendar.month_abbr[x])
most_sold['period'] = most_sold['month_name'] + ' ' + most_sold['year'].astype(str)

print(most_sold[['period', 'code', 'qty']])

     period      code   qty
0  Oct 2025  10016728    24
1  Nov 2025  10019275    56
2  Jan 2026  10022091    84
3  Feb 2026  10022578    60
4  Mar 2026  10025542    71
5  Apr 2026    500001  1032